In [11]:
%matplotlib qt 
import pandas as pd
import glob
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
#import matplotlib.gridspec as gridspec
#import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic

In [2]:
# Reading the already Processed and merged file
mergedDfFromFile=pd.read_csv('D:\\DataScienceAtNP\\BuyFi\\mergedData.csv', header = 0)

C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
mergedDfFromFile['TR_DATE'] = mergedDfFromFile['TR_DATE'].apply(pd.to_datetime , errors='coerce')
uniqueMerchantIds=mergedDfFromFile.merchantId.unique()
resultData =[]
for merchantId in uniqueMerchantIds:
    merchantDf=mergedDfFromFile[mergedDfFromFile['merchantId']==merchantId]
    totTxn=merchantDf['TR_AMOUNT'].sum()
    totTxnInEve=len(merchantDf[merchantDf['TR_DATE'].dt.hour >13])
    totTxnInMorn=len(merchantDf[merchantDf['TR_DATE'].dt.hour <14])
    totTxnValueInEve= (merchantDf[merchantDf['TR_DATE'].dt.hour >13])['TR_AMOUNT'].sum()
    totTxnValueInMorn= (merchantDf[merchantDf['TR_DATE'].dt.hour <14])['TR_AMOUNT'].sum()
    uniqueCustomers=merchantDf.CID.unique()
    meanArr=[]
    for customer in uniqueCustomers :
        custTempDf=merchantDf[merchantDf['CID']==customer]
        mean=custTempDf['TR_AMOUNT'].mean()
        meanArr.append(mean)
    dfMean = pd.DataFrame(meanArr)
    median=dfMean[0].median()
    noOfCustomers=len(uniqueCustomers)
    averageTxn=totTxn/(len(merchantDf))
    tempDf=merchantDf[merchantDf['TR_DATE'].dt.month>0]
    tempDf2=tempDf[merchantDf['TR_DATE'].dt.month<4]
    groupedDf=tempDf2.groupby(tempDf2.TR_DATE.dt.year)
    summ=0
    #doing this so that total quarter value only consists for a year not for all years
    length= len(groupedDf)
    if(length<>0):
        for x in groupedDf.groups.keys():
            y=groupedDf.get_group(x)
            summ=summ+ y['TR_AMOUNT'].sum()
        firstQuarter=summ/length
    else :
        firstQuarter=0
    summ=0
    length=0
    tempDf=merchantDf[merchantDf['TR_DATE'].dt.month>3]
    tempDf2=tempDf[merchantDf['TR_DATE'].dt.month<7]
    groupedDf=tempDf2.groupby(tempDf2.TR_DATE.dt.year)
    length= len(groupedDf)
    if(length<>0):
        for x in groupedDf.groups.keys():
            y=groupedDf.get_group(x)
            summ=summ+ y['TR_AMOUNT'].sum()
        secondQuarter=summ/length
       
    else :
         secondQuarter=0
    summ=0        
    tempDf=merchantDf[merchantDf['TR_DATE'].dt.month>6]
    tempDf2=tempDf[merchantDf['TR_DATE'].dt.month<10]
    groupedDf=tempDf2.groupby(tempDf2.TR_DATE.dt.year)
    length= len(groupedDf)
    if(length<>0):
        for x in groupedDf.groups.keys():
            y=groupedDf.get_group(x)
            summ=summ+ y['TR_AMOUNT'].sum()
        thirdQuarter=summ/length
    else :
         thirdQuarter=0
            
    tempDf=merchantDf[merchantDf['TR_DATE'].dt.month>9]
    tempDf2=tempDf[merchantDf['TR_DATE'].dt.month<13]
    summ=0
    groupedDf=tempDf2.groupby(tempDf2.TR_DATE.dt.year)
    length= len(groupedDf)
    if(length<>0):
        for x in groupedDf.groups.keys():
            y=groupedDf.get_group(x)
            summ=summ+ y['TR_AMOUNT'].sum()
        fourthQuarter=summ/length
    else :
        fourthQuarter=0
    weekdayDf=merchantDf[merchantDf['TR_DATE'].dt.dayofweek<5]
    totTxnOnWeekday=weekdayDf['TR_AMOUNT'].sum()
    weekendDf=merchantDf[merchantDf['TR_DATE'].dt.dayofweek>4]
    totTxnOnWeekend=weekendDf['TR_AMOUNT'].sum()
    noOfWeekendTxn=len(weekendDf)
    noOfWeekdayxn=len(weekdayDf)
    if(noOfWeekendTxn<>0) :
        avgTxnOnWeekend=totTxnOnWeekend/noOfWeekendTxn
    else :
        avgTxnOnWeekend=0
    if(noOfWeekdayxn<>0) :
        avgTxnOnWeekday=totTxnOnWeekday/noOfWeekdayxn
    else :
        avgTxnOnWeekday=0  
    weekdayTxnMedian=weekdayDf['TR_AMOUNT'].median()
    weekendTxnMedian=weekendDf['TR_AMOUNT'].median()
    dataObj={'AvPerCust':median,'MerchantId':merchantId,'TotTxnValue':totTxn,'TotNoOfTxnInMorn':totTxnInMorn,'WeekdayTxnMedian':weekdayTxnMedian,'WeekendTxnMedian':weekendTxnMedian,'TotNoOfTxnInEve':totTxnInEve,'TotTxnValueInMorn':totTxnValueInMorn,'TotTxnOnWeekday':totTxnOnWeekday,'TotTxnOnWeekend':totTxnOnWeekend,'AvgTxnOnWeekday':avgTxnOnWeekday,'AvgTxnOnWeekend':avgTxnOnWeekend,'TotTxnValueInEve':totTxnValueInEve,'NoOfCustomers':noOfCustomers,'AverageTxn':averageTxn,'Q1':firstQuarter,
             'Q2':secondQuarter,'Q3':thirdQuarter,'Q4':fourthQuarter}
    resultData.append(dataObj)
df = pd.DataFrame(resultData)
finalDf=df[['MerchantId','NoOfCustomers','AverageTxn','AvPerCust','TotTxnValue','TotNoOfTxnInEve','TotNoOfTxnInMorn','TotTxnValueInMorn','TotTxnValueInEve','TotTxnOnWeekday','TotTxnOnWeekend','AvgTxnOnWeekday','AvgTxnOnWeekend','WeekendTxnMedian','WeekdayTxnMedian','Q1','Q2','Q3','Q4']]
finalDf.head()

C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\ipykernel\__main__.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\ipykernel\__main__.py:49: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\ipykernel\__main__.py:61: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,MerchantId,NoOfCustomers,AverageTxn,AvPerCust,TotTxnValue,TotNoOfTxnInEve,TotNoOfTxnInMorn,TotTxnValueInMorn,TotTxnValueInEve,TotTxnOnWeekday,TotTxnOnWeekend,AvgTxnOnWeekday,AvgTxnOnWeekend,WeekendTxnMedian,WeekdayTxnMedian,Q1,Q2,Q3,Q4
0,08X7QBXBM8M78,737,109.715623,66.00,137363.96,976,276,25848.12,111515.84,100414.72,36949.24,109.742863,109.641662,63.37,64.80,10737.663333,14214.363333,10272.12,15845.760
1,GBFTFE1YBP566,2776,101.390072,72.00,467813.79,3748,866,79936.97,387876.82,319515.63,148298.16,98.161484,109.123002,69.00,69.00,37368.080000,51102.443333,38163.11,43956.445
2,0B5AHDRMT87KW,53,91.571818,58.25,6043.74,58,8,785.52,5258.22,3220.50,2823.24,74.895349,122.749565,66.72,50.00,0.000000,4637.140000,1406.60,0.000
3,0RSGGCC4BHXDA,7995,30.305689,11.71,1060365.76,25116,9873,320321.10,740044.66,775334.02,285031.74,30.473373,29.858762,17.05,16.49,130068.305000,133820.335000,90255.09,130911.605
4,1MF9X4PFDFJX8,1761,17.405138,13.00,53555.61,1209,1868,32840.48,20715.13,34691.07,18864.54,17.790292,16.738722,14.00,14.37,6653.135000,9129.315000,4962.84,12065.030

In [6]:
finalDf.to_csv('D:\\DataScienceAtNP\\BuyFi\\1\\buyFiAnalysis.csv',index=False)

In [7]:
mergedDfFromFile=pd.read_csv('D:\\DataScienceAtNP\\BuyFi\\1\\buyFiAnalysis.csv', header = 0)

In [8]:
#Taking only those merchants whose transactions are more than 2000

mergedDfFromFile1=mergedDfFromFile[mergedDfFromFile['TotTxnValue']>2000]

# adding average values for missing quarters

for index , row in mergedDfFromFile1.iterrows():
    q1=mergedDfFromFile1.ix[index].Q1
    q2=mergedDfFromFile1.ix[index].Q2
    q3=mergedDfFromFile1.ix[index].Q3
    q4=mergedDfFromFile1.ix[index].Q4
    tot=0
    count=0
    if(q1<>0) :
        tot=tot+q1
        count=count+1
    if(q2<>0) :
        tot=tot+q2
        count=count+1
    if(q3<>0) :
        tot=tot+q3
        count=count+1
    if(q4<>0) :
        tot=tot+q4
        count=count+1
    avg=tot/count
    if(q1==0):
        mergedDfFromFile1.set_value(index,'Q1',avg)
    if(q2==0):
        mergedDfFromFile1.set_value(index,'Q2',avg)
    if(q3==0):
        mergedDfFromFile1.set_value(index,'Q3',avg)
    if(q4==0):
        mergedDfFromFile1.set_value(index,'Q4',avg)
mergedDfFromFile1.head()

,MerchantId,NoOfCustomers,AverageTxn,AvPerCust,TotTxnValue,TotNoOfTxnInEve,TotNoOfTxnInMorn,TotTxnValueInMorn,TotTxnValueInEve,TotTxnOnWeekday,TotTxnOnWeekend,AvgTxnOnWeekday,AvgTxnOnWeekend,WeekendTxnMedian,WeekdayTxnMedian,Q1,Q2,Q3,Q4
0,08X7QBXBM8M78,737,109.715623,66.00,137363.96,976,276,25848.12,111515.84,100414.72,36949.24,109.742863,109.641662,63.37,64.80,10737.663333,14214.363333,10272.12,15845.760
1,GBFTFE1YBP566,2776,101.390072,72.00,467813.79,3748,866,79936.97,387876.82,319515.63,148298.16,98.161484,109.123002,69.00,69.00,37368.080000,51102.443333,38163.11,43956.445
2,0B5AHDRMT87KW,53,91.571818,58.25,6043.74,58,8,785.52,5258.22,3220.50,2823.24,74.895349,122.749565,66.72,50.00,3021.870000,4637.140000,1406.60,3021.870
3,0RSGGCC4BHXDA,7995,30.305689,11.71,1060365.76,25116,9873,320321.10,740044.66,775334.02,285031.74,30.473373,29.858762,17.05,16.49,130068.305000,133820.335000,90255.09,130911.605
4,1MF9X4PFDFJX8,1761,17.405138,13.00,53555.61,1209,1868,32840.48,20715.13,34691.07,18864.54,17.790292,16.738722,14.00,14.37,6653.135000,9129.315000,4962.84,12065.030

In [9]:
# just writing the file so that whole processing not required again
mergedDfFromFile1.to_csv('D:\\DataScienceAtNP\\BuyFi\\1\\buyFiAnalysis2.csv',index=False)

In [12]:
# Just experimenting with min max scaler
scaler = MinMaxScaler()
dfScaleTest=pd.DataFrame(['NoOfCustomers'])
mergedDfFromFile1[['AverageTxn']]=scaler.fit_transform(mergedDfFromFile1[['AverageTxn']])
mergedDfFromFile1.head()

C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\shashank\AppData\Local\Enthought\Canopy\User\lib\site-packages\pandas\core\indexing.py:461: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,MerchantId,NoOfCustomers,AverageTxn,AvPerCust,TotTxnValue,TotNoOfTxnInEve,TotNoOfTxnInMorn,TotTxnValueInMorn,TotTxnValueInEve,TotTxnOnWeekday,TotTxnOnWeekend,AvgTxnOnWeekday,AvgTxnOnWeekend,WeekendTxnMedian,WeekdayTxnMedian,Q1,Q2,Q3,Q4
0,08X7QBXBM8M78,737,0.279306,66.00,137363.96,976,276,25848.12,111515.84,100414.72,36949.24,109.742863,109.641662,63.37,64.80,10737.663333,14214.363333,10272.12,15845.760
1,GBFTFE1YBP566,2776,0.256869,72.00,467813.79,3748,866,79936.97,387876.82,319515.63,148298.16,98.161484,109.123002,69.00,69.00,37368.080000,51102.443333,38163.11,43956.445
2,0B5AHDRMT87KW,53,0.230409,58.25,6043.74,58,8,785.52,5258.22,3220.50,2823.24,74.895349,122.749565,66.72,50.00,3021.870000,4637.140000,1406.60,3021.870
3,0RSGGCC4BHXDA,7995,0.065299,11.71,1060365.76,25116,9873,320321.10,740044.66,775334.02,285031.74,30.473373,29.858762,17.05,16.49,130068.305000,133820.335000,90255.09,130911.605
4,1MF9X4PFDFJX8,1761,0.030533,13.00,53555.61,1209,1868,32840.48,20715.13,34691.07,18864.54,17.790292,16.738722,14.00,14.37,6653.135000,9129.315000,4962.84,12065.030